In [5]:
import pickle 
import pandas as pd
import sys
import os
current_dir = os.getcwd()
parent_dir = os.path.dirname(current_dir)
sys.path.append(parent_dir)
parent_dir = os.path.dirname(parent_dir)
sys.path.append(f'{parent_dir}/VEBGLM/src')
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import pickle

import matplotlib.pyplot as plt 
import seaborn as sns

In [6]:
datasets_name = ['adult', 'annealing', 'Ionosphere', 'heart_disease', 'abalone', 'Pediatric']

In [19]:

pd.set_option('display.max_rows', None)
res_all = []
for data_name in datasets_name:
    with open(f'{current_dir}/results/{data_name}-final.pkl', 'rb') as f:
        res = pickle.load(f)
    res_all = res_all + res


results_df = pd.DataFrame(res_all)

In [21]:
results_df = results_df.drop(['data_name'], axis=1)

In [34]:
res = results_df.groupby(['model', 'metric']).mean().reset_index()

In [35]:
res[res['metric'] == 'precision_score']

                   model           metric  rep     score   run_time  seed
2                L0Learn  precision_score  9.5  0.856355  26.704104   9.5
7                    MCP  precision_score  9.5  0.858259  65.074276   9.5
12                  SCAD  precision_score  9.5  0.859430  67.735167   9.5
17            VEBGLM-ash  precision_score  9.5  0.858269  11.728096   9.5
22  VEBGLM-point_laplace  precision_score  9.5  0.860522  28.106983   9.5
27   VEBGLM-point_normal  precision_score  9.5  0.859190  14.587465   9.5
32            elasticnet  precision_score  9.5  0.864662  43.921384   9.5
37                 lasso  precision_score  9.5  0.869654   3.973151   9.5
42                varbvs  precision_score  9.5  0.856657  13.319202   9.5

In [29]:
res = results_df.groupby(['model', 'metric']).std().reset_index()
res[res['metric'] == 'f1_score']

                   model    metric       rep     score    run_time      seed
1                L0Learn  f1_score  5.790459  0.109566   35.857233  5.790459
6                    MCP  f1_score  5.790459  0.102828  154.380803  5.790459
11                  SCAD  f1_score  5.790459  0.102756  159.572587  5.790459
16            VEBGLM-ash  f1_score  5.790459  0.106039    9.771867  5.790459
21  VEBGLM-point_laplace  f1_score  5.790459  0.109145   28.427483  5.790459
26   VEBGLM-point_normal  f1_score  5.790459  0.106232   15.442577  5.790459
31            elasticnet  f1_score  5.790459  0.139791   87.188508  5.790459
36                 lasso  f1_score  5.790459  0.111659    6.865524  5.790459
41                varbvs  f1_score  5.790459  0.105572   19.061768  5.790459

In [25]:
res[res['metric'] == 'roc_auc_score']

                   model         metric  rep     score   run_time  seed
4                    MCP  roc_auc_score  9.5  0.911533  62.814556   9.5
9                   SCAD  roc_auc_score  9.5  0.914731  66.063672   9.5
14            VEBGLM-ash  roc_auc_score  9.5  0.920632  10.832319   9.5
19  VEBGLM-point_laplace  roc_auc_score  9.5  0.921313  26.055126   9.5
24   VEBGLM-point_normal  roc_auc_score  9.5  0.920580  13.553056   9.5
29                 lasso  roc_auc_score  9.5  0.920375   3.836298   9.5
34                 ridge  roc_auc_score  9.5  0.914756   5.779661   9.5
39                varbvs  roc_auc_score  9.5  0.917967   7.923638   9.5

In [27]:
res = results_df.groupby(['model', 'metric']).std().reset_index()
res[res['metric'] == 'roc_auc_score']

,model,metric,rep,score,run_time,seed
4,MCP,roc_auc_score,5.790459,0.040064,148.461663,5.790459
9,SCAD,roc_auc_score,5.790459,0.038930,155.662400,5.790459
14,VEBGLM-ash,roc_auc_score,5.790459,0.043087,9.031540,5.790459
19,VEBGLM-point_laplace,roc_auc_score,5.790459,0.043517,25.977578,5.790459
24,VEBGLM-point_normal,roc_auc_score,5.790459,0.043376,14.192421,5.790459
29,lasso,roc_auc_score,5.790459,0.044581,6.669425,5.790459
34,ridge,roc_auc_score,5.790459,0.045807,12.156918,5.790459
39,varbvs,roc_auc_score,5.790459,0.044046,15.525705,5.790459